<a href="https://colab.research.google.com/github/Shiva-Gangadhar/Movie-Recommendation-System/blob/main/Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movies_data=pd.read_csv('/content/movies.csv')


In [3]:
movies_data.head()

index     budget  ...                                               crew           director
0      0  237000000  ...  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1      1  300000000  ...  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2      2  245000000  ...  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3      3  250000000  ...  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4      4  260000000  ...  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton

[5 rows x 24 columns]

In [4]:
movies_data.shape

(4803, 24)

In [31]:
selected_features = ['genres', 'keywords','overview','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'overview', 'tagline', 'cast', 'director']


In [32]:
for feature in selected_features:
  movies_data[feature]=movies_data[feature].fillna('')

In [33]:
combined_features=movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['overview']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [34]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      When ambitious New York attorney Sam is sent...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [35]:
vectorizer=TfidfVectorizer()
feature_vectors=vectorizer.fit_transform(combined_features)

In [36]:
print(feature_vectors)

  (0, 561)	0.05971816344971169
  (0, 703)	0.06846420517510078
  (0, 9754)	0.08513696797398294
  (0, 23977)	0.07941905576010944
  (0, 10023)	0.07960231361105431
  (0, 6601)	0.1498786462809525
  (0, 5279)	0.1549075340655008
  (0, 10796)	0.11095111375730655
  (0, 25413)	0.24369151759694266
  (0, 29469)	0.08637114089261566
  (0, 5592)	0.17322386697661618
  (0, 25232)	0.1336739112380023
  (0, 13474)	0.03647840985795873
  (0, 27118)	0.08328687324810813
  (0, 239)	0.19716936546022962
  (0, 4768)	0.12501550204808315
  (0, 20104)	0.19260031442011954
  (0, 17021)	0.14324534514274753
  (0, 14023)	0.041700928584839175
  (0, 7827)	0.1797988202434295
  (0, 27405)	0.0310150192195571
  (0, 18249)	0.14769810641761003
  (0, 20039)	0.37747447361884223
  (0, 19541)	0.04908322232312576
  (0, 28597)	0.1549075340655008
  :	:
  (4802, 9588)	0.10415492266309316
  (4802, 21386)	0.08975511036766048
  (4802, 9166)	0.07829183421073847
  (4802, 24102)	0.08207980733784753
  (4802, 6136)	0.10774075928383217
  (4802, 

In [37]:
similarity=cosine_similarity(feature_vectors)

In [38]:
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [39]:
similarity.shape

(4803, 4803)

In [41]:
movie=input('Enter your favourite Movie: ')

Enter your favourite Movie: Bat Man


In [42]:
list_of_all_movies=movies_data['title'].tolist()
print(list_of_all_movies)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [43]:
find_close_match=difflib.get_close_matches(movie,list_of_all_movies)
print(find_close_match)

['Batman', 'Batman', 'Rain Man']


In [44]:
close_match=find_close_match[0]
print(close_match)

Batman


In [45]:
index_of_the_movie=movies_data[movies_data['title'] == close_match]['index'].values[0]
print(index_of_the_movie)

1359


In [46]:
similarity_score=list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.030860719934350737), (1, 0.05456461098791574), (2, 0.025420994912788583), (3, 0.2338052098853376), (4, 0.0358579417889144), (5, 0.06480779316059049), (6, 0.025328125342328544), (7, 0.031193482768275965), (8, 0.07596121965157163), (9, 0.13026811298484625), (10, 0.07833585908102393), (11, 0.03140815118288081), (12, 0.046352500640976665), (13, 0.020981937983779262), (14, 0.08730563650625815), (15, 0.045390479826427535), (16, 0.04552566681084561), (17, 0.05419186846387077), (18, 0.05218562648148115), (19, 0.04606592690189089), (20, 0.0525972351819297), (21, 0.051347408495229015), (22, 0.02839994503747764), (23, 0.019972687270657253), (24, 0.03409065291411044), (25, 0.03537669989730546), (26, 0.03301451878795811), (27, 0.03862483049353923), (28, 0.009394777698689412), (29, 0.027117087927202004), (30, 0.11255005372745663), (31, 0.02385466070349696), (32, 0.05433211054681876), (33, 0.013086526824339497), (34, 0.008338950414900109), (35, 0.043018081030419646), (36, 0.0708976060335784), 

In [47]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1],reverse=True)
print(sorted_similar_movies)

[(1359, 1.0), (428, 0.2617904941926373), (119, 0.24169629159349437), (210, 0.23658744402159052), (3, 0.2338052098853376), (65, 0.19739154749412363), (3854, 0.17189148066390786), (299, 0.17131588130636344), (9, 0.13026811298484625), (30, 0.11255005372745663), (72, 0.11188219858913873), (1469, 0.10632393464294962), (41, 0.09937847357289423), (813, 0.09831507541115998), (1512, 0.09722485277470566), (2381, 0.09504139941592654), (1390, 0.09212763468361622), (4759, 0.09119404017361916), (1001, 0.09045240143423047), (870, 0.0901958374513215), (1017, 0.08998086162656344), (2858, 0.08816994503073253), (14, 0.08730563650625815), (1247, 0.08650870548084974), (753, 0.08580678946933294), (1421, 0.08488904988897164), (2365, 0.08348512466950818), (3819, 0.08346778604898233), (3297, 0.08312337849316276), (4183, 0.08234811260685254), (3068, 0.08148501232489744), (1803, 0.08148108286462766), (2029, 0.08124850902763674), (4392, 0.08059207903276856), (800, 0.08043228229246674), (2822, 0.08019374012931646)

In [48]:
print('Movies recommended for you: \n')

i=1

for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=movies_data[movies_data['index']==index]['title'].values[0]
  if(i<=30):
    print(i,'.',title_from_index)
    i+=1

Movies recommended for you: 

1 . Batman
2 . Batman Returns
3 . Batman Begins
4 . Batman & Robin
5 . The Dark Knight Rises
6 . The Dark Knight
7 . Batman: The Dark Knight Returns, Part 2
8 . Batman Forever
9 . Batman v Superman: Dawn of Justice
10 . Spider-Man 2
11 . Suicide Squad
12 . Chill Factor
13 . Green Lantern
14 . Superman
15 . A History of Violence
16 . Salton Sea
17 . Underworld: Rise of the Lycans
18 . The Image Revolution
19 . Street Fighter: The Legend of Chun-Li
20 . Superman II
21 . Bedazzled
22 . The Postman Always Rings Twice
23 . Man of Steel
24 . City By The Sea
25 . The Sentinel
26 . Hoffa
27 . Nine 1/2 Weeks
28 . Defendor
29 . The Death and Life of Bobby Z
30 . Hang 'em High


In [51]:
movie=input('Enter your favourite Movie: ')

find_close_match=difflib.get_close_matches(movie,list_of_all_movies)

close_match=find_close_match[0]

index_of_the_movie=movies_data[movies_data['title'] == close_match]['index'].values[0]

similarity_score=list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1],reverse=True)

print('Movies recommended for you: \n')

i=1

for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=movies_data[movies_data['index']==index]['title'].values[0]
  if(i<=30):
    print(i,'.',title_from_index)
    i+=1

Enter your favourite Movie: Iron Man
Movies recommended for you: 

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Avengers: Age of Ultron
5 . The Avengers
6 . X-Men
7 . The Helix... Loaded
8 . Captain America: Civil War
9 . X-Men: Apocalypse
10 . Ant-Man
11 . Made
12 . Guardians of the Galaxy
13 . X-Men: Days of Future Past
14 . Super
15 . Mortdecai
16 . The Incredible Hulk
17 . Mystery Men
18 . Captain America: The Winter Soldier
19 . The Devil's Tomb
20 . X-Men: First Class
21 . Kick-Ass 2
22 . Spider-Man 2
23 . Sliding Doors
24 . X-Men: The Last Stand
25 . X2
26 . Sin City
27 . Hellboy II: The Golden Army
28 . G-Force
29 . The Nativity Story
30 . Surf's Up


I have a thought that I can extend this project to develop netflix clone or amazon prime clone by creating Good user interface(UI/UX designing). If possible I can increase my dataset which covers some more movies.